print("Programming***Essentials***in...", end="")
print("Python")

print("I'm student")
print('\'\'I\'m"\n""learning""\n"""Python"""')
print("        *")
print("     *    *")
print("   *        *")
print(" *            *")
print("*****      *****")
print("     *     *")
print("     ******* ")
octal_value = int('500', 8)
print(octal_value)
hex_value = int('777', 16)
print(hex_value)